---
baseurl: "http://soapy.pb.co.za/"
languageCode: "en-us"
title: "Soapy"
editor: "emacs -nw"
metaDataFormat: "yaml"
theme: "soapy.pb.co.za-hugo-theme"
publishdir: "public"
indexes:
  category: "categories"
  tag: "tags"
author:
  name: "Pieter Breed"
---
