---
# baseurl: "" # leave this unset
languageCode: "en-us"
title: "The Amazing Soap Shop"
metaDataFormat: "yaml"
theme: "strata"
  "params": {
    "name": "Your name",
    "description": "Describe your website",
    "googleAnalytics": "",
    "sidebar": {
      "avatar": "avatar.jpg",
      "bio": "**I'm Strata**, a super simple<br> responsive site template freebie<br> crafted by [HTML5 UP](//html5up.net).",
      "twitter": "spf13",
      "github": "spf13",
      "dribbble": "",
      "facebook": "",
      "copyright": [
        "&copy; John Doe",
        "Design: [HTML5 UP](//html5up.net)",
        "Demo Images: [Unsplash](//unsplash.com/)"
      ]
    },
    "about": {
      "title": "Ipsum lorem dolor aliquam ante commodo magna sed accumsan arcu neque.",
      "content": "Accumsan orci faucibus id eu lorem semper. Eu ac iaculis ac nunc nisi lorem vulputate lorem neque cubilia ac in adipiscing in curae lobortis tortor primis integer massa adipiscing id nisi accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque cubilia."
    },
    "portfolio": {
      "title": "Recent Work"
    },
    "contact": {
      "title": "Get In Touch",
      "content": "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor.",
      "address": [
        "1234 Somewhere Rd.",
        "Nashville, TN 00000",
        "United States"
      ],
      "phone": "000-000-0000",
      "email": "hello@example.com",
      "form": {
        "name": "Name",
        "email": "Email",
        "message": "Message",
        "submit": "Send message"
      }
    }
  },
  "[params": {
    "portfolio": {
      "gallery": {
        "image": "fulls/06.jpg",
        "thumb": "thumbs/06.jpg",
        "title": "Lorem ipsum dolor.",
        "description": "Lorem ipsum dolor sit amet."
      }
    }
  }

  
