# baseurl = "http://replace-this-with-your-hugo-site.com/"
languageCode = "en-us"
title = "The Amazing Soap Shop"
theme = "strata"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Pieter Breed"
	description = "Boutique Soap eCommerce"
        googleAnalytics = "UA-73172604-1"

	[params.sidebar]
		avatar = "avatar.jpg"
		bio = "Hi! I'm **Pieter**. It feels *Good* to be *Kind* to others. &#x1f60c;"
		twitter = "amazingsoapshop"
		github = "pieterbreed"
		instagram = "theamazingsoapshop"
		facebook = ""

                content = "[most recent newsletter](/newsletter/welcome)"

		copyright = [
			"&copy; Pieter Breed",
			"[![CC-BY-SA](/images/cc-by-sa.png)](//creativecommons.org/licenses/by-sa/4.0/)"
		]


	[params.about]
		title = "The Amazing Soap Shop"
		content = "Because **Gifting** good soap to someone is an act of **Kindness**."
                product_brand_copy = "Our soap is made with pure oils chosen for their skin loving properties. Fragrancing is done with Essential Oils only and no artificial fragrances are used. Fragrancing is always very subtle in order to prevent the possibility of allergic reactions on sensitive skin. All the soaps are made using the Cold Process method. All recipes are calculated in order that the final soap will not only clean your skin, but it will feed it as well so that in the end you will have a softer, healthier skin."

	[params.contact]
		title = "Get In Touch"
		content = "You can use this form to send me an email."

		address = [
                        "Greenpoint",
                        "Cape Town",
                        "South Africa"
		]
		phone = "+28 82 567 6207"
		email = "pieter@theamazingsoapshop.co.za"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "eg. Pieter Breed"
			email = "eg. pieter@theamazingsoapshop.co.za"
			message = "Message"
			submit = "Send message"
