---
# baseurl: "" # leave this unset
languageCode: "en-us"
title: "The Amazing Soap Shop"
metaDataFormat: "yaml"
theme: "theme"
indexes:
  category: "categories"
  tag: "tags"
author:
  name: "Pieter Breed"
---
