---
# baseurl: "http://soapy.pb.co.za/" # leave this unset
languageCode: "en-us"
title: "Soapy"
metaDataFormat: "yaml"
theme: "theme"
publishdir: "../../output/hugo"
indexes:
  category: "categories"
  tag: "tags"
author:
  name: "Pieter Breed"
---
