---
- hosts: webserver
  vars:
    vhost: "{{ lookup('env', 'WEBSERVER_PUBLIC_DNSNAME') }}"
    port:  "{{ lookup('env', 'WEBSERVER_PUBLIC_PORT') }}"
  tasks:
    - name: Update the nginx default config file
      template:
        src: "nginx.conf.j2"
        dest: "{{ nginx_config_path }}/sites-available/default"
      notify:
        - reload nginx
    - name: Copy the static content accross
      debug: msg="at a later stage, let this actually copy something somewhere"
      when: false
  handlers:
    - name: reload nginx
      shell: nginx -s reload
