---
- hosts: all
  tasks:
    - name: Make extra ips available to eth0
      notify:
        - reboot
      template:
        src: interface_d.cfg.j2
        dest: "{{ ip.conf_d_folder }}/{{ item.interface_nr }}.cfg"
      with_items: extra_ips
  handlers:
    - name: reboot
      shell: "reboot"
          
