---
- hosts: webserver
  tasks:
    - name: "Install nginx"
      apt:
        name: nginx
        state: present

    - name: Test current nginx config
      shell: "nginx -t"
      changed_when: false
      tags:
        - nginx-config

    - name: Set the nginx site config file for webserver
      template:
        src: "nginx-conf/nginx_webserver.conf.j2"
        dest: "{{ nginx.config_dir }}/sites-available/webserver.conf"
      notify:
        - reload nginx
      tags:
        - nginx-config
        
    - name: Set the sites-enabled symlink for webserver
      file:
        src: "{{ nginx.config_dir }}/sites-available/webserver.conf"
        dest: "{{ nginx.config_dir }}/sites-enabled/webserver.conf"
        state: link
      notify:
        - reload nginx
      tags:
        - nginx-config
        
    - name: "Make sure nginx is at least running"
      service:
        name: nginx
        state: started
        enabled: yes

  handlers:
    - name: reload nginx
      service:
        name: nginx
        state: reloaded
        
