---
- hosts: all
  tasks:
    - name: "Copy my public ssh key over"
      authorized_key:
        exclusive: yes
        key: "{{ github_keys_file }}"
        state: present
        user: "{{ ansible_user_id }}"

- hosts: all
  vars:
    sshd:
      X11Forwarding: no
      PrintMotd: yes
  roles:
    - willshersystems.sshd
