---
- hosts: all
  tasks:
    - name: Update the system to the bleeding edge
      apt:
        cache_valid_time: 3600
        force: yes
        install_recommends: yes
        update_cache: yes
        upgrade: full
        state: latest
    - name: Install coreutils
      apt:
        name: "{{ item }}"
        state: present
      with_items:
        - tree
        - coreutils
